---
- name: Enterprise Security Hardening & Compliance
  hosts: all
  become: yes
  tasks:
    - name: ğŸ›¡ï¸ Apply Critical OS Security Patches
      package:
        name: "*"
        state: latest
      when: ansible_os_family in ["RedHat", "Debian"]

    - name: ğŸ” SSH Hardening - Disable Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: ğŸ“Š Setup Observability (Prometheus Node Exporter)
      package:
        name: prometheus-node-exporter
        state: present
      ignore_errors: yes

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
